/** Domain types for the MRV module, aligned to the mrv schema (Appendix B). */

export type QuantApproach = "QA1" | "QA2" | "QA3";
export type ClimateZone = "wet" | "dry";
export type ProjectStatus =
  | "under_development"
  | "registered"
  | "validated"
  | "verified";

export interface Project {
  projectId: string;
  name: string;
  methodology: string;
  isGrouped: boolean;
  country: string;
  status: ProjectStatus;
  isDemo: boolean;
}

export interface Farm {
  farmId: string;
  projectId: string;
  name: string;
  installationCode: string;
  operator: string | null;
  country: string;
  region: string | null;
  climateZone: ClimateZone;
  status: string;
  isDemo: boolean;
  /** derived */
  plotCount: number;
  totalAreaHa: number;
}

/** A GeoJSON Polygon, as stored (SRID 4326). */
export interface PolygonGeoJSON {
  type: "Polygon";
  coordinates: number[][][];
}

export interface Plot {
  plotId: string;
  farmId: string;
  name: string;
  geom: PolygonGeoJSON;
  areaHa: number;
  applicationAreaHa: number;
  quantificationApproach: QuantApproach;
  crop: string | null;
  strokeColor: string;
  isDemo: boolean;
}

/** A farm with its plots, for the map / overview. */
export interface FarmWithPlots extends Farm {
  plots: Plot[];
}

/** mrv.point_status */
export type PointStatus = "planned" | "sampled" | "lab_pending" | "complete";
/** mrv.sample_scenario */
export type SampleScenario = "BSL" | "PR" | "WP";

export interface SamplingPoint {
  pointId: string;
  plotId: string | null;
  bslId: string | null;
  scenario: SampleScenario;
  /** [lon, lat] of planned_geom */
  lonLat: [number, number];
  compositeCores: number | null;
  isRevisit: boolean;
  status: PointStatus;
}

/* ───────────────── Plot Details (spec §6.3) ───────────────── */

/** mrv.products — the agri-input catalogue behind Project Activities. */
export interface Product {
  name: string;
  activityType: string;
  activityLabel: string;
  costPerHaUsd: number | null;
  /** ex-ante tCO2e/ha shown on the marketplace */
  creditPerHa: number | null;
}

/** mrv.alm_activities — a Project Activity applied to one plot. */
export interface AlmActivity {
  activityId: string;
  plotId: string;
  product: Product | null;
  activityType: string;
  rate: number | null;
  rateUnit: string | null;
  applicationAreaHa: number | null;
  applicationDate: string | null;
  season: string | null;
  /** 'PR' with-project, 'BSL' baseline */
  scenario: SampleScenario;
  notes: string | null;
}

/** One sample taken at a point (mrv.samples + its sampling_event). */
export interface SampleRow {
  sampleId: string;
  pointId: string;
  sampleType: "soc" | "texture";
  stratumCode: string | null;
  scenario: SampleScenario;
  depthTopCm: number | null;
  depthBaseCm: number | null;
  compositeCores: number | null;
  barcode: string | null;
  samplingDate: string | null;
  /** from the sampling event */
  distanceFromTargetM: number | null;
  photoUrl: string | null;
  fieldNotes: string | null;
}

/** mrv.soc_measurements — one lab row per depth increment. */
export interface SocMeasurement {
  sampleId: string;
  method: string;
  analysisDate: string | null;
  depthTopCm: number;
  depthBaseCm: number;
  bulkDensity: number | null;
  toc400Pct: number | null;
  roc600Pct: number | null;
  tic900Pct: number | null;
  /** generated: TOC400 + ROC600 */
  tocPct: number | null;
  /** generated, fixed-depth basis */
  socTPerHa: number | null;
  soilMassTHa: number | null;
}

/** mrv.texture_measurements */
export interface TextureMeasurement {
  sampleId: string;
  sandPct: number;
  siltPct: number;
  clayPct: number;
  /** generated by mrv.usda_texture_class() */
  usdaClass: string;
  depthCm: number | null;
}

/** mrv.model_runs, summarised for the plot pane. */
export interface ModelRunSummary {
  runId: string;
  model: string;
  modelVersion: string | null;
  runType: string | null;
  scenario: string;
  status: string;
  uncertaintyMethod: string | null;
  monteCarloIters: number | null;
  periodStart: string | null;
  periodEnd: string | null;
}

/* ─────────── Sampling plans / cycles (spec §6.4) ─────────── */

/** mrv.cycle_type */
export type CycleType = "initial" | "true_up" | "verification";
/** mrv.cycle_status */
export type CycleStatus =
  | "draft"
  | "approved"
  | "in_field"
  | "lab_pending"
  | "complete"
  | "cancelled";

/** mrv.sampling_cycles — one planned sampling round for a farm. */
export interface SamplingPlan {
  cycleId: string;
  farmId: string;
  farmName: string;
  projectId: string;
  cycleNumber: number;
  cycleType: CycleType;
  approach: QuantApproach;
  collectTexture: boolean;
  textureDepthCm: number | null;
  triggerType: string | null;
  depthScheme: string;
  plannedStart: string | null;
  plannedEnd: string | null;
  confidenceAlpha: number | null;
  power: number | null;
  mddTarget: number | null;
  sameSeason: boolean;
  revisitPoints: boolean;
  status: CycleStatus;
  generatedBy: string;
  approvedAt: string | null;
  /** points planned for this cycle */
  plannedPoints: number;
}

/* ─────────── Work orders & MCP tokens (spec §6.5, §9) ─────────── */

/** mrv.wo_state */
export type WorkOrderState = "draft" | "sent" | "in_progress" | "completed" | "closed";

/** mrv.labs — the destination laboratory. */
export interface Lab {
  labId: string;
  name: string;
  iso17025: boolean;
  naptMember: boolean;
  glosolanMember: boolean;
  defaultMethod: string | null;
  contact: string | null;
}

/** mrv.mcp_tokens — scoped, revocable field access. Never holds the raw token. */
export interface McpToken {
  tokenId: string;
  workOrderId: string;
  contractorEmail: string | null;
  issuedAt: string;
  expiresAt: string;
  revokedAt: string | null;
  lastUsedAt: string | null;
}

/** A row of the work order's sampling-points table. */
export interface WorkOrderPoint {
  sampleId: string;
  pointId: string;
  stratumCode: string | null;
  scenario: SampleScenario;
  lat: number;
  lon: number;
  depthScheme: string;
  compositeCores: number | null;
  isRevisit: boolean;
}

/** mrv.work_orders */
export interface WorkOrder {
  woId: string;
  farmId: string;
  farmName: string;
  cycleId: string;
  cycleNumber: number;
  cycleType: CycleType;
  approach: QuantApproach;
  contractorName: string | null;
  contractorEmail: string | null;
  lab: Lab | null;
  projectLead: string | null;
  windowStart: string | null;
  windowEnd: string | null;
  depthScheme: string;
  state: WorkOrderState;
  pdfUrl: string | null;
  issuedAt: string | null;
  closedAt: string | null;
  points: WorkOrderPoint[];
  token: McpToken | null;
}

/** Everything the Plot Details screen needs, in one payload. */
export interface PlotDetail {
  plot: Plot;
  farm: Farm;
  points: SamplingPoint[];
  samples: SampleRow[];
  soc: SocMeasurement[];
  texture: TextureMeasurement[];
  activities: AlmActivity[];
  modelRuns: ModelRunSummary[];
}
